# Generated by Django 5.1.5 on 2025-02-08 20:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basemodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basemodels.buyerbase')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('payment_terms', models.CharField(choices=[('upfront', 'Upfront'), ('credit', 'Credit'), ('any', 'Any')], default='any', max_length=10)),
                ('preferred_order_quantity', models.PositiveIntegerField(default=1)),
                ('order_frequency', models.CharField(choices=[('Weekly', 'weekly'), ('Annually', 'annually'), ('Daily', 'daily'), ('Monthly', 'monthly')], default='weekly', max_length=20)),
                ('can_arrange_transport', models.BooleanField(default=False)),
            ],
            bases=('basemodels.buyerbase',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basemodels.productbase')),
            ],
            bases=('basemodels.productbase',),
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('buyer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recsys.buyer')),
                ('siege_number', models.IntegerField()),
                ('market_name', models.CharField(max_length=100)),
            ],
            bases=('recsys.buyer',),
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('buyer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recsys.buyer')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
            ],
            bases=('recsys.buyer',),
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basemodels.farmerbase')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('min_quantity_order', models.PositiveIntegerField(default=1)),
                ('delivery_region', models.PositiveIntegerField(default=50)),
                ('offers_delivery', models.BooleanField(default=False)),
                ('payment_terms', models.CharField(choices=[('upfront', 'Upfront'), ('credit', 'Credit'), ('any', 'Any')], default='any', max_length=10)),
                ('buyer_choice', models.CharField(choices=[('personal', 'Personal'), ('market', 'Market'), ('both', 'Both')], default='both', max_length=10)),
                ('supply_frequency', models.CharField(choices=[('Weekly', 'weekly'), ('Annually', 'annually'), ('Daily', 'daily'), ('Monthly', 'monthly')], default='weekly', max_length=20)),
                ('products', models.ManyToManyField(to='recsys.product')),
            ],
            bases=('basemodels.farmerbase',),
        ),
        migrations.AddField(
            model_name='buyer',
            name='preferred_products',
            field=models.ManyToManyField(to='recsys.product'),
        ),
    ]
