# Generated by Django 5.1.4 on 2025-01-31 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='personal',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='longitude',
        ),
        migrations.AddField(
            model_name='buyer',
            name='can_arrange_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='buyer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='buyer',
            name='order_frequency',
            field=models.CharField(choices=[('Weekly', 'weekly'), ('Annually', 'annually'), ('Daily', 'daily'), ('Monthly', 'monthly')], default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='buyer',
            name='payment_terms',
            field=models.CharField(choices=[('upfront', 'Upfront'), ('credit', 'Credit'), ('any', 'Any')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='buyer',
            name='preferred_order_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='farmer',
            name='buyer_choice',
            field=models.CharField(choices=[('personal', 'Personal'), ('market', 'Market'), ('both', 'Both')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='farmer',
            name='delivery_region',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='farmer',
            name='min_quantity_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='farmer',
            name='offers_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='payment_terms',
            field=models.CharField(choices=[('upfront', 'Upfront'), ('credit', 'Credit'), ('any', 'Any')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='farmer',
            name='supply_frequency',
            field=models.CharField(choices=[('Weekly', 'weekly'), ('Annually', 'annually'), ('Daily', 'daily'), ('Monthly', 'monthly')], default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='buyer',
            name='preferred_products',
            field=models.ManyToManyField(to='Branch.product'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='products',
            field=models.ManyToManyField(to='Branch.product'),
        ),
    ]
